Feat: add signup and login implement with test
BrewInteractive/authentication-service-nestjs pull request #17
Opened 2023-03-28 12:29 UTC by mehmetsagdur

2023-04-07 13:25 UTC, mfozmen requested changes

2023-04-07 13:25 UTC, mfozmen commented on src/token/token.service.ts
> +  async createToken(user, expiresIn: number) {
user'ın type'ı eksik burada. buraya bir dto ile taşımak lazım. automapper falan kullansak daha iyi olur dto ile taşırken.

https://medium.com/@exfabrica/nestjs-dto-with-automapper-c4e89009f30b

2023-04-07 13:25 UTC, mfozmen commented on src/user/user.service.spec.ts
> +      passwordHash: await bcrypt.hash(faker.internet.password(), 10),
zaten bcrypt'i mocklamışız. gerçek bcrypt bağımlılığı yaratmamalıyız.

2023-04-19 08:33 UTC, ismetkizgin commented on src/auth/auth.controller.spec.ts
> +          provide: "TokenService",
fonksiyonlarını tek tek mock'lamak yerine genel olarak servisi çağırabilirsin burada. Aşağıdaki gibi olabilir providers değeri. 
`
SignUpProfile,
LoginProfile,
TokenService,
UserService
`

2023-04-19 08:37 UTC, ismetkizgin commented on src/auth/auth.controller.spec.ts
> +      imports: [
Modül ile aynı şekilde buranın kurgulanması gerekiyor. Testlerinde o şekilde çalışması lazım. auth.module.ts'e bakıp o şekilde burann refactor edilmesi gerekiyor.

2023-04-19 08:43 UTC, ismetkizgin commented on src/user/user.module.ts
> +import { Module } from "@nestjs/common";
user.module için test yazılması gerekiyor.

2023-04-19 08:43 UTC, ismetkizgin commented on src/auth/auth.module.ts
>  import { AuthController } from "./auth.controller";
auth module için test yazılması gerekiyor.

2023-04-19 08:43 UTC, ismetkizgin commented on src/user/user.service.ts
> +  async getUser(username: string, email: string): Promise<User> {
async methodlarda method isminin sonuna Async ekleyelim.

2023-04-25 06:38 UTC, ismetkizgin approved these changes

2023-04-27 06:48 UTC, merged