Ts 202 create an email service that sends an html e mail in authentication service
BrewInteractive/authentication-service-nestjs pull request #34
Opened 2023-10-19 08:16 UTC by erailea

2023-10-19 11:33 UTC, mfozmen requested changes

2023-10-19 11:33 UTC, mfozmen commented on src/email/interfaces/email.service.interface.ts
> +export abstract class BaseEmailService {
"EmailService" is enough for naming.

2023-10-19 11:33 UTC, mfozmen commented on src/email/interfaces/email.service.interface.ts
> +export abstract class BaseEmailService {
This shouldn't be named as interface. It should be email.service.ts and it should be under email folder, not email/interfaces.

2023-10-19 11:33 UTC, mfozmen commented on src/email/aws.email.service.ts
> +export class AwsEmailService extends BaseEmailService {
"aws-email.service" is a better naming for the file. Also, we can move this service under email/providers folder.

2023-10-19 11:33 UTC, mfozmen commented on src/email/aws.email.service.ts
> +  constructor(@InjectMapper() private readonly mapper: Mapper) {
We can get configurations as a AwsEmailConfig class in constructor. We shouldn't reach config directly from here. Instead, we can set this configurations while importing AwsEmailService provider in EmailModule.

2023-10-19 21:01 UTC, erailea commented on src/email/interfaces/email.service.interface.ts
> +export abstract class BaseEmailService {
`abstract class BasePlugin`

2023-10-20 08:12 UTC, mfozmen requested changes

2023-10-20 08:12 UTC, mfozmen commented on src/email/interfaces/email.service.interface.ts
> +export interface IEmailService {
Since we have already abstract EmailService class, we don't need this interface. We can remove it.

2023-10-20 08:12 UTC, mfozmen commented on src/email/interfaces/aws-email.config.interface.ts
> +export interface IAwsEmailConfig {
Rename this interface as AwsEmailConfig since it's the recommended naming convention in NestJs. I will fix IPlugin naming also.

2023-10-20 09:04 UTC, erailea commented on src/email/aws-email.service.ts
> +    @Inject("IAwsEmailConfig") private readonly awsConfig: IAwsEmailConfig
couldnt resolve but it will stay that way for now

2023-10-20 09:05 UTC, erailea commented on src/email/aws-email.service.ts
> +      region: awsConfig.region,
since awsConfig is not an instance it is not necessary but done

2023-10-23 07:08 UTC, mfozmen approved these changes

2023-10-23 07:09 UTC, merged