feat(TS-241): implemented createRefreshTokenAsync func.
BrewInteractive/authentication-service-nestjs pull request #43
Opened 2023-11-07 18:25 UTC by katafalque

feaT(https://brewww.atlassian.net/browse/TS-241) : function to get refresh token

2023-11-08 06:33 UTC, ismetkizgin commented on src/token/token.service.ts
> +    return refreshToken || null;
user information should not be returned

2023-11-14 09:51 UTC, ismetkizgin approved these changes

2023-11-14 12:40 UTC, mfozmen requested changes

2023-11-14 14:15 UTC, mfozmen approved these changes

2023-11-14 14:15 UTC, merged