feat(TS-187): create refresh-token module
BrewInteractive/authentication-service-nestjs pull request #45
Opened 2023-11-15 06:40 UTC by ismetkizgin

2023-11-16 13:57 UTC, mehmetsagdur approved these changes

2023-11-17 10:49 UTC, mfozmen requested changes

2023-11-17 10:49 UTC, mfozmen commented on src/refresh-token/refresh-token.controller.ts
> +    return { refreshToken };
We should return both a new refresh and id token.

2023-11-17 11:10 UTC, mfozmen approved these changes
There are some missing features but they will be completed TS-253

2023-11-17 11:10 UTC, merged