Feature/create otp module
BrewInteractive/authentication-service-nestjs pull request #83
Opened 2024-05-02 09:07 UTC by ismetkizgin

2024-05-02 20:15 UTC, katafalque approved these changes

2024-05-07 11:18 UTC, mfozmen requested changes

2024-05-07 11:18 UTC, mfozmen commented on test/fixtures/otp/otp.fixture.ts
> +  withEmailChannel(size: number = 2) {
What's "size" for?

2024-05-07 12:03 UTC, mfozmen approved these changes

2024-05-07 12:06 UTC, merged