Feature/create login otp email controller
BrewInteractive/authentication-service-nestjs pull request #85
Opened 2024-05-02 12:14 UTC by ismetkizgin

2024-05-02 20:48 UTC, katafalque approved these changes

2024-05-07 07:08 UTC, erailea commented on src/login/login-otp-email.controller.ts
> +    const isItConfirmed = await this.otpService.validateEmailOtpAsync(
isConfirmed, isOtpConfirmed seems better naming

2024-05-08 12:31 UTC, mfozmen requested changes

2024-05-08 12:31 UTC, mfozmen commented on src/login/login-otp-email.controller.ts
> +    return await this.tokenService.createTokensAsync(user);
Check if the user exists.

2024-05-08 12:31 UTC, mfozmen commented on test/integration/login-otp-email.e2e-spec.ts
> +      const mockUser = MockFactory(UserFixture).one().hashPassword();
General note for namings. Do not name as mockUser, mockOtp etc. Define the variable well. Which user is it? Which otp is it? Name it well for better understanding the test.

2024-05-08 12:31 UTC, mfozmen commented on test/integration/login-otp-email.e2e-spec.ts
> +    it("Should return a token if OTP credentials are valid", async () => {
should return tokens if otp is valid

2024-05-08 12:31 UTC, mfozmen commented on test/integration/login-otp-email.e2e-spec.ts
> +    it("Should return a token if OTP credentials are valid", async () => {
Add user not found case test also.

2024-05-09 11:58 UTC, mfozmen approved these changes

2024-05-09 12:01 UTC, mfozmen approved these changes

2024-05-09 12:08 UTC, merged