feat(VILLB-6): create send login otp email controller and test cases.
BrewInteractive/authentication-service-nestjs pull request #87
Opened 2024-05-09 20:06 UTC by katafalque

2024-05-10 07:12 UTC, ismetkizgin commented on src/login/login.module.ts
> +  imports: [TokenModule, UserModule, OtpModule, EventEmitterModule.forRoot()],
`EventEmitterModule.forRoot()` is defined in the `app` module. Let's remove this definition.

2024-05-10 07:44 UTC, ismetkizgin commented on src/login/send-otp-email-login.controller.ts
> +    const sendOtpResult = await this.otpService.createEmailOtpAsync(sendLoginOtpEmailRequest.email);
There is otpValue in the otp result. otpValue should not be sent in the response.

2024-05-10 07:46 UTC, ismetkizgin requested changes

2024-05-10 07:46 UTC, ismetkizgin commented on src/login/send-otp-email-login.controller.ts
> +      this.eventEmitter.emit("otp.email.created", otpEmailCreatedEvent);
refactor:

```
this.eventEmitter.emit("otp.email.created", {
        otpValue: sendOtpResult.otpValue,
        emailAddress: sendLoginOtpEmailRequest.email,
        authenticationAction: AuthenticationAction.LOGIN,
      });
```

2024-05-10 07:49 UTC, ismetkizgin commented on test/integration/send-otp-email-login.e2e-spec.ts
> +        expect(responseEmail.body).toHaveProperty("otpValue");
In the response, there should be no otpValue.

2024-05-10 10:24 UTC, ismetkizgin requested changes

2024-05-10 10:24 UTC, ismetkizgin commented on src/login/dto/send-login-otp-email-response.dto.ts
> +  is_sent: boolean;
Let's name it using camelCase naming convention.

2024-05-10 10:24 UTC, ismetkizgin commented on test/integration/send-otp-email-login.e2e-spec.ts
> +        expect(responseEmail.body).toHaveProperty("expires_at");
Could you check if the date is greater than the current time?

2024-05-10 10:24 UTC, ismetkizgin commented on src/login/dto/send-login-otp-email-response.dto.ts
> +  expires_at: Date;
Let's name it using camelCase naming convention.

2024-05-10 11:42 UTC, mfozmen requested changes

2024-05-10 11:42 UTC, mfozmen commented on src/login/dto/send-login-otp-email-request.dto.spec.ts
> +describe("LoginDto Validation", () => {
SendLoginOtpEmailRequest validation

2024-05-10 11:42 UTC, mfozmen commented on src/login/dto/send-login-otp-email-request.dto.spec.ts
> +      const user = new SendLoginOtpEmailRequest();
user? it should be request at least.

2024-05-10 11:42 UTC, mfozmen commented on src/login/dto/send-login-otp-email-request.dto.spec.ts
> +      const user = new SendLoginOtpEmailRequest();
user? it should be request at least.

2024-05-10 11:42 UTC, mfozmen commented on src/login/dto/send-login-otp-email-response.dto.spec.ts
> +  it("should create a LoginResponse object with optional properties", () => {
LoginResponse -> SendLoginOtpEmailResponse

2024-05-10 11:42 UTC, mfozmen commented on src/login/send-otp-email-login.controller.spec.ts
> +import {
Rename the file as send-login-otp-email.controller.spec.ts

2024-05-10 11:42 UTC, mfozmen commented on src/login/send-otp-email-login.controller.ts
> +import { Inject, Controller, Post, Body, UnauthorizedException } from "@nestjs/common";
Rename the file as send-login-otp-email.controller.ts

2024-05-10 11:42 UTC, mfozmen commented on src/login/send-otp-email-login.controller.spec.ts
> +  describe("SendLoginOtpEmailController", () => {
Rename all mock variables better. Define the variable. For example mockUser doesn't define the user. If it's a valid user then rename as validUser or if it's an invalid user rename as invalidUser like that.

2024-05-10 11:42 UTC, mfozmen commented on src/login/send-otp-email-login.controller.ts
> +    if(!user) throw new UnauthorizedException("User doesn't exist.");
Remove user doesn't exist message for now. In future this can be handled while sending e-mail.

2024-05-13 07:57 UTC, mfozmen approved these changes

2024-05-13 08:03 UTC, merged