remove: remove for MySQL configuration and migration files
BrewInteractive/authentication-service-nestjs pull request #89
Opened 2024-05-13 10:07 UTC by mehmetsagdur

2024-05-13 14:21 UTC, erailea approved these changes

2024-05-14 10:02 UTC, ismetkizgin requested changes

2024-05-14 10:02 UTC, ismetkizgin commented on docs/local_development.md
>  $ npm run migration-postgres:generate
Migration name parameter is missing. Can we add it too?

2024-05-14 11:20 UTC, ismetkizgin approved these changes

2024-05-14 13:27 UTC, merged