feat(VILLB-18): add exceptions filter, BREAKING CHANGE: change http e…
BrewInteractive/authentication-service-nestjs pull request #96
Opened 2024-05-14 07:17 UTC by katafalque

…xceptions in services to custom errors.

2024-05-14 12:17 UTC, ismetkizgin requested changes

2024-05-14 12:17 UTC, ismetkizgin commented on src/exception/invalid-credentials.error.ts
> +export class InvalidCredentialsError extends Error {
Can we make the Expection nomenclature and the class from which it is inherited as in the nestjs document? 

https://docs.nestjs.com/exception-filters#custom-exceptions

2024-05-14 12:17 UTC, ismetkizgin commented on src/exception/invalid-otp.error.ts
> +export class InvalidOtpError extends Error {
Can we make the Expection nomenclature and the class from which it is inherited as in the nestjs document? 

https://docs.nestjs.com/exception-filters#custom-exceptions

2024-05-14 12:17 UTC, ismetkizgin commented on src/exception/invalid-refresh-token.error.ts
> +export class InvalidRefreshTokenError extends Error {
Can we make the Expection nomenclature and the class from which it is inherited as in the nestjs document? 

https://docs.nestjs.com/exception-filters#custom-exceptions

2024-05-14 12:17 UTC, ismetkizgin commented on src/exception/invalid-reset-password-request.error.ts
> +export class InvalidResetPasswordRequestError extends Error {
Can we make the Expection nomenclature and the class from which it is inherited as in the nestjs document? 

https://docs.nestjs.com/exception-filters#custom-exceptions

2024-05-14 12:17 UTC, ismetkizgin commented on src/exception/invalid-user.error.ts
> +export class InvalidUserError extends Error {
Can we make the Expection nomenclature and the class from which it is inherited as in the nestjs document? 

https://docs.nestjs.com/exception-filters#custom-exceptions

2024-05-14 12:17 UTC, ismetkizgin commented on src/exception/user-exists.error.ts
> +export class UserExistsError extends Error {
Can we make the Expection nomenclature and the class from which it is inherited as in the nestjs document? 

https://docs.nestjs.com/exception-filters#custom-exceptions

2024-05-14 12:17 UTC, ismetkizgin commented on src/exception/user-not-found.error.ts
> +export class UserNotFoundError extends Error {
Can we make the Expection nomenclature and the class from which it is inherited as in the nestjs document? 

https://docs.nestjs.com/exception-filters#custom-exceptions

2024-05-14 12:17 UTC, ismetkizgin commented on src/filter/exceptions.filter.ts
> +export class ExceptionsFilter implements ExceptionFilter {
Expection classes will have status information. Can we review the example and update it according to the incoming data? 

https://docs.nestjs.com/exception-filters#exception-filters-1

2024-05-14 12:17 UTC, ismetkizgin commented on src/refresh-token/refresh-token.controller.ts
> +  @UseFilters(new ExceptionsFilter())
Let's not use the Expection filter property in this way. We can define it globally only once in Main. 

`app.useGlobalFilters(new HttpExceptionFilter());`

2024-05-15 15:13 UTC, mfozmen commented
It will decline after merging this: https://github.com/BrewInteractive/authentication-service-nestjs/pull/99

2024-05-16 15:13 UTC, closed without merging

2024-05-16 15:14 UTC, mfozmen commented
will merge this https://github.com/BrewInteractive/authentication-service-nestjs/pull/99 instead of this pr.